# Pandas_DataFrame and Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structure: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (row and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\swapn\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\swapn\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\swapn\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\swapn\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\swapn\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

### Series 
A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

In [5]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
## Create a Series from dictionary
data = {'a':1, 'b': 2, 'c':3}
series_dict = pd.Series(data)
print("Series from dictionary \n", series_dict)

# a,b,c are index and 1,2,3 are values. We can also specify our own index.

Series from dictionary
 a    1
b    2
c    3
dtype: int64

In [8]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

### DataFrame

`A DataFrame is a two-dimensional`,<br>`size-mutable, and potentially heterogeneous tabular data structure with labeled axes (row and columns)`. <br>`It is similar to a spreadsheet or SQL table.`

In [27]:
## DataFrame
## Create a DataFrame from dictionary of list.

data={
    'Name': ['Swapnil', 'Rahul', 'Priya'],
    'Age': [25,30,22],
    'City': ['Pune', 'Mumbai', 'Delhi']
}
 # 3 columns and 3 rows. Name, Age, City are column names and Swapnil, Rahul, Priya are values in Name column. 25,30,22 are values in Age column and Pune, Mumbai, Delhi are values in City column.

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi
<class 'pandas.core.frame.DataFrame'>

In [15]:
import numpy as np
np.array(df)
# We can also use numpy array to create a DataFrame. We need to specify column names and index.
# It will skip the first row and first column and will take the rest of the data to create a DataFrame. We can also specify our own index and column names.

array([['Swapnil', 25, 'Pune'],
       ['Rahul', 30, 'Mumbai'],
       ['Priya', 22, 'Delhi']], dtype=object)

In [25]:
## Create a DataFrame from list of dictionaries.
data = [
    {'Name': 'Swapnil', 'Age': 25, 'City': 'Pune'},
    {'Name': 'Rahul', 'Age': 30, 'City': 'Mumbai'},
    {'Name': 'Priya', 'Age': 22, 'City': 'Delhi'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi
<class 'pandas.core.frame.DataFrame'>

In [23]:
df = pd.read_csv('sales_data.csv')
# print(df.head(5))
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [24]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

#### Accessing data from DataFrame

In [29]:
df

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi

In [31]:
df['Name'] # Accessing a column

0    Swapnil
1      Rahul
2      Priya
Name: Name, dtype: object

In [33]:
df.loc[0] # Accessing a row index

Name    Swapnil
Age          25
City       Pune
Name: 0, dtype: object

In [34]:
df.iloc[0] # Accessing a row index using iloc

Name    Swapnil
Age          25
City       Pune
Name: 0, dtype: object

 we used iloc for slicing the data. We can also use loc for slicing the data. The difference between loc and iloc is that loc is label based and iloc is integer based. loc will include the end index while slicing and iloc will exclude the end index while slicing.

In [35]:
df.iloc[0][1]

25

In [36]:
df.iloc[0][0]

'Swapnil'

In [37]:
## Accessing a specified element
df['Name']

0    Swapnil
1      Rahul
2      Priya
Name: Name, dtype: object

In [39]:
df

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi

In [40]:
df.at[1,'Age'] # it will access the Age's 1 index.

30

In [41]:
df.at[2,'Name']

'Priya'

In [43]:
## Accessing a specific element using iat

df.iat[2,2]

'Delhi'

In [44]:
## Data Manipulation with DataFrame
df

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi

In [56]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

      Name  Age    City  Salary
0  Swapnil   25    Pune   50000
1    Rahul   30  Mumbai   60000
2    Priya   22   Delhi   70000

In [49]:
## Remove a column
df.drop('Salary',axis = 1)

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi

In [52]:
df    #Salary again come
      # drop is a temporary operation.
      # we need to use `inplace` to do permanent opration.

      Name  Age    City  Salary
0  Swapnil   25    Pune   50000
1    Rahul   30  Mumbai   60000
2    Priya   22   Delhi   70000

In [57]:
df.drop('Salary',axis = 1,inplace=True)

In [58]:
df

      Name  Age    City
0  Swapnil   25    Pune
1    Rahul   30  Mumbai
2    Priya   22   Delhi

In [61]:
## Add age to the column
df['Age'] = df['Age']+1

In [62]:
df

      Name  Age    City
0  Swapnil   26    Pune
1    Rahul   31  Mumbai
2    Priya   23   Delhi

In [63]:
df.drop(0)

    Name  Age    City
1  Rahul   31  Mumbai
2  Priya   23   Delhi

In [64]:
df

      Name  Age    City
0  Swapnil   26    Pune
1    Rahul   31  Mumbai
2    Priya   23   Delhi

In [67]:
df.drop(0,inplace = True)

In [68]:
df

    Name  Age    City
1  Rahul   31  Mumbai
2  Priya   23   Delhi

In [69]:
df = pd.read_csv('sales_data.csv')
# print(df.head(5))
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [76]:
# Display the data type of each column
print("Data type:\n",df.dtypes)

## Describe the DataFrame
print("Statistical summary: \n",df.describe())

## Group by a column an perform and aggregation
grouped = df.groupby('Catagory')['Value'].mean()
print("Mean value by category:\n",grouped)

Data type:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

KeyError: 'Catagory'

In [78]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000